### ISSUE TITLE
Doesn't output errors in watch mode

### ISSUE THREAD

**Issue by eXaminator** [voxpelli/node-test-pretty-reporter#10]
If I run node tests via the following code:

```
run({
    files,
    watch: true,
})
    .compose(reporter)
    .pipe(process.stdout);
```

I will get the red output that a test failed, but I get no error of what failed exactly. Can this be fixed? It does work with the default spec reporter.

**Comment by voxpelli** [comment]
I think this is the same cause as the one in #16 which #17 fixed. It should be released in 1.1.2. If it doesn't fix it, then please comment – or even better, open a new issue here (since only I can reopen and I may miss the notification among my currently 723 unread github notifications)
